version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  dispatcher:
    build:
      context: .
      dockerfile: Dockerfile-go
      target: dispatcher
    ports:
      - "8080:8080"

  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile-go
      target: pocketbase
    ports:
      - "8090:8090"

