version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  dispatcher:
    build:
      context: ./cmd/dispatcher
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  pocketbase:
    build:
      context: ./cmd/pocketbase
      dockerfile: Dockerfile
    ports:
      - "8090:8090"

  web:
    build:
      context: ./cmd/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./cmd/web:/app